### ISSUE TITLE
Error 502 / Cert cannot updated

### ISSUE THREAD

**Issue by ghost** [mmccarn/sophos#3]
Hello. I have the Sophos XG (SFOS 18.0.4 MR-4).

If I want to update a Cert, then I get the Error 502. (Name is allready exists) Must I delete the old cert?

Best regard.
DanVanBurgh

**Comment by mmccarn** [comment]
I found on my firewall (running SFOS 17.5.x) that it was not possible to use the API to update a certificate that was actually in use. Additionally, I have not  found any way to use the API to re-assign the certificate for an existing WAF rule.

Taken together, these two limitations make this process somewhat useless...

I've updated the script on my local system to create the new cert with the current date in the certificate name, but this still leaves me needing to login to the firewall to edit every rule using the old cert to assign the new cert. Frustrating.

I'll update the cert here in github now.

**Comment by mmccarn** [comment]
You should be able to load the new certificates into the XG if you download and use the new versions of le2xg.sh and xgxml.txt, but as mentioned above this still leaves you manually changing the certificates for any entry in the firewall that is using them.

Note: when you change the cert in a WAF rule in the XG, the rule defaults to using every domain listed in the certificate.  If you are using one LetsEncrypt certificate for multiple services, you need to delete from each WAF rule the domain names that do not apply to that rule.
