### ISSUE TITLE
Error 529

### ISSUE THREAD

**Issue by Dume91** [mmccarn/sophos#4]
Hello,

I am looking to use le2xg.sh on my sophos XG (SFOS 18.0.5 MR-5).
When I run the command './le2xg.sh add'
I have a message : 

<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Status code="529">Input request file is Invalid</Status>
</Response>

**Comment by mmccarn** [comment]
I've updated [le2xg.sh](https://github.com/mmccarn/sophos/blob/master/le2xg.sh) to include this block immediately above "# cert date" to set a value for the variable I added two weeks ago (doh!)

```
# Letsencrypt CertificateAuthority
# CA will be created in Sophos as ${LECertAuth}-yymmdd
LECertAuth=LE 
```
