### ISSUE TITLE
Error in sed command creates duplicate XML

### ISSUE THREAD

**Issue by nedashley** [mmccarn/sophos#5]
Hi,

Thank you for the script, when using it I was getting the error:

`<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Status code="529">Input request file is Invalid</Status>
</Response>`

After changing this part of the script from:

`sed \
  -e "s/APIUSER/$APIUSER/" \
  -e "s/APIPLAINPASS/$APIPLAINPASS/" \
  -e "s/OPERATION/$OPERATION/" \
  -e "s/LEDOMAIN/$LEDOMAIN-$CERTDATE/" ${XML} \
  -e "s/LECertAuth/$LECertAuth-$CERTDATE/" ${XML} \
| curl -k -F "reqxml=<-" \
  -F file=@/etc/letsencrypt/live/$LEDOMAIN/chain.pem \
  -F file=@/etc/letsencrypt/live/$LEDOMAIN/fullchain.pem \
  -F file=@./privkey.key \
  "https://$ROUTER/webconsole/APIController?"`

To:

`sed \
  -e "s/APIUSER/$APIUSER/" \
  -e "s/APIPLAINPASS/$APIPLAINPASS/" \
  -e "s/OPERATION/$OPERATION/" \
  -e "s/LEDOMAIN/$LEDOMAIN-$CERTDATE/" \
  -e "s/LECertAuth/$LECertAuth-$CERTDATE/" ${XML} \
| curl -k -F "reqxml=<-" \
  -F file=@/etc/letsencrypt/live/$LEDOMAIN/chain.pem \
  -F file=@/etc/letsencrypt/live/$LEDOMAIN/fullchain.pem \
  -F file=@./privkey.key \
  "https://$ROUTER/webconsole/APIController?"`

It is now working.

Thanks

**Comment by mmccarn** [comment]
Thanks. I've updated the script.
